name: 'Auto Assign'
on:
  workflow_call:
    inputs:
      reviewers:
        required: true
        type: string
        description: "Comma-separated list of reviewers"
    secrets:
      token_for_github_api:
        description: 'Token to use for GitHub API'
        required: true

jobs:
  assign-reviewers:
    runs-on: ubuntu-latest
    steps:
    
    - name: Check Branch Protection & General Repository Settings
      uses: 'SaaS-Innova/github-action@main'
      with:
        repository: ${{ github.repository }}
        token_for_github_api: ${{ secrets.token_for_github_api }}

    - name: Assign Reviewers
      uses: actions/github-script@v6
      with:
        script: |
          const reviewers = "${{ inputs.reviewers }}".split(',').map(r => r.trim()); // Parse input
          console.log("Reviewers to assign:", reviewers);
          const prAuthor = context.payload.pull_request.user.login; // Get PR author
          console.log("PR Author:", prAuthor);
          const filteredReviewers = reviewers.filter(r => r !== prAuthor); // Exclude PR author
          console.log("Filtered Reviewers:", filteredReviewers);
          if (filteredReviewers.length === 0) {
            console.log("No valid reviewers to assign.");
            return; // Exit if no valid reviewers
          }
          await github.rest.pulls.requestReviewers({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.payload.pull_request.number,
            reviewers: filteredReviewers,
          });
  

