name: 'Auto Assign'
on:
  workflow_call:
    inputs:
      reviewers:
        required: true
        type: string
        description: "Comma-separated list of reviewers"
    secrets:
      token:
        required: true

permissions:
  pull-requests: write

jobs:
  add-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Add Reviewers
        uses: buzato/add-reviewer-gh-action@1.0.5
        with:
          reviewers: ${{ inputs.reviewers }}
          token: ${{ secrets.token }}

