name: Deploy to Glesys STAGE

on:
  workflow_call:
    inputs:
      hostname:
        required: true
        type: string
        description: "The hostname for the server"
      user:
        required: true
        type: string
        description: "The user for SSH"
      target:
        required: true
        type: string
        description: "The target environment"
      destination:
        required: true
        type: string
        description: "Destination path on the server"
      fingerprint:
        required: true
        type: string
        description: "SSH fingerprint"
      pm2_name:
        required: true
        type: string
        description: "Name for the pm2 process"
      mode:
        required: true
        type: string
        description: "The mode for the deployment"
    secrets:
      password:
        required: true
        description: "The password for the server"
      dotenv_key:
        required: true
        description: "The key for the dotenv file"
      dotenv_me:
          required: true
          description: "The dotenv me key for the dotenv file"
      token_for_github_api:
        description: 'Token to use for GitHub API'
        required: true

jobs:
  deploy:
    uses: 'SaaS-Innova/github-action/.github/workflows/deploy-backend.yml@main'
    with:
      hostname: ${{ inputs.hostname }}
      user: ${{ inputs.user }}
      target: ${{ inputs.target }}
      destination: ${{ inputs.destination }}
      fingerprint: ${{ inputs.fingerprint }}
      pm2_name: ${{ inputs.pm2_name }}
      mode: ${{ inputs.mode }}
    secrets:
      password: ${{ secrets.password }}
      dotenv_key: ${{ secrets.dotenv_key }} 
      dotenv_me: ${{ secrets.dotenv_me }}
      token_for_github_api: ${{ secrets.token_for_github_api }}