name: 'Prettier dry run'

# This makes the workflow reusable
on:
  workflow_call:  # Add this line
    inputs:
      prettier_options:
        description: 'Options to pass to Prettier'
        required: false
        default: '--check **/*.tsx'
        type: string
    secrets:
      token:
        description: 'Token to use for GitHub API'
        required: false

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      
      # - name: Set GitHub Token
      #   id: set-token
      #   run: |
      #     if [ -z "${{ secrets.token }}" ]; then
      #       echo "Using given token."
      #       echo "token=${{ secrets.token }}" >> $GITHUB_ENV
      #     else
      #       echo "Using repository token."
      #       echo "token=${{ secrets.PERSONAL_TOKEN_FOR_WORKFLOW }}" >> $GITHUB_ENV


      - name: Check Branch Protection
        uses: 'SaaS-Innova/github-action@main'
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.token }}
          branches: 'main,development'

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          dry: True
          only_changed: true
          prettier_options: ${{ inputs.prettier_options }}
