name: 'Prettier dry run'

# This makes the workflow reusable
on:
  workflow_call:  # Add this line
    inputs:
      prettier_options:
        description: 'Options to pass to Prettier'
        required: false
        default: '--check **/*.tsx'
        type: string
    secrets:
      token_for_github_api:
        description: 'Token to use for GitHub API'
        required: true

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Check Branch Protection & General Repository Settings
        uses: 'SaaS-Innova/github-action@main'
        with:
          repository: ${{ github.repository }}
          token_for_github_api: ${{ secrets.token_for_github_api }}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          dry: True
          only_changed: true
          prettier_options: ${{ inputs.prettier_options }}
