name: 'Validate Translation Action'

on:
  workflow_call: 
    secrets:
      token_for_github_api:
        description: 'Token to use for GitHub API'
        required: true

jobs:
  validate-translations:
    runs-on: ubuntu-latest
    steps:
      - name: Check Branch Protection & General Repository Settings
        uses: 'SaaS-Innova/github-action@main'
        with:
          repository: ${{ github.repository }}
          token_for_github_api: ${{ secrets.token_for_github_api }}

      - name: Checkout calling repository (Caller Repo)
        uses: actions/checkout@v3
        with:
          path: ${{ github.workspace }}

      - name: Checkout reusable workflow repository
        uses: actions/checkout@v3
        with:
          repository: 'SaaS-Innova/github-action'
          path: 'SaaS-Innova/github-action'
          
      - name: Validate translation files
        run: node SaaS-Innova/github-action/.github/scripts/validate-translations.js
        env:
          I18N_PATH: ${{ github.workspace }}/src/i18n
